### ISSUE TITLE
What should the Device Playback Test Environment look like?

### ISSUE THREAD

**Issue by andyburras** [cta-wave/test-and-compliance-task-force#5]
Assumption is that we are wanting to start with something simple and straightforward, rather than an "all singing and dancing" solution.
The WAVE Test Approach document includes a logical diagram that was driven by the initial use cases collected.

Discussions on TCTF calls concluded that the simplest approach would be

- the test software running on the device under test.
- For MSE based testing, using a very minimal CMAF "Media Player" that feeds the MSE/API. In practice there may be several variations of this to meet different testing requirements.

The original diagram has been revised to reflect this approach.

TBD: Review of this by TCTF, DPCTF and TWG.

**Comment by bobcampbell-resillion** [comment]
I think this is too broad a question to have useful discussion in this format. suggest we resolve this in the Test Spec, and raise more specific questions about the test environment here.

**Comment by andyburras** [comment]
Agreed. The outputs from discussions in the TCTF call are now in the Testing document and the architecture diagram has been circulated to TCTF and DPCTF for comment. I'll close this.
