### ISSUE TITLE
DRM License Server Requirements

### ISSUE THREAD

**Issue by andyburras** [cta-wave/test-and-compliance-task-force#7]
Current suggestion is that Fairplay, PlayReady, Widevine modular, and Marlin DRM schemes shall be supported.

TBD: This is the subject of ongoing discussions for the preparation of an letter to request voluntary resources from 3rd parties

**Comment by bobcampbell-resillion** [comment]
I propose resolving this unless there's a question to be answered. I think its assumed the DRM server supplier will provide what is requested - and at least one is needed. A better question might be whether the testing should include ClearKey.

**Comment by andyburras** [comment]
I think HATF have established that ClearKey testing will form part of the Web Media API testing. Expectation is that there will be existing W3C tests that use this for the API conformance testing (TBD, whether there are  any other forms of DRM testing in the W3C suite and whether they are required in the final WAVE test suite subset).

**Comment by andyburras** [comment]
Note there is now an ongoing email thread around DRM that may make this clearer.

**Comment by andyburras** [comment]
Following an email discussion in TCTF (see https://standards.cta.tech/apps/org/workgroup/tctf/message.php/201803/msg00020.html ), it appears to be clear that "real" DRM testing will be required within the Device Playback Testing environment. I will capture this in the TCTF document and close this issue.
